
import {getApps, initializeApp, cert, App} from 'firebase-admin/app';
import type { ServiceAccount } from 'firebase-admin';

// DO NOT EDIT. This file is generated by Firebase App Hosting.
function getServiceAccount(): ServiceAccount | undefined {
  const serviceAccount = process.env.FIREBASE_SERVICE_ACCOUNT;
  if (!serviceAccount) return undefined;
  try {
    return JSON.parse(serviceAccount);
  } catch (e) {
    console.error("Failed to parse FIREBASE_SERVICE_ACCOUNT:", e);
    return undefined;
  }
}

let app: App | undefined = undefined;

export function initializeFirebaseAdmin(): App | undefined {
  if (app) {
    return app;
  }
  
  if (getApps().length) {
    app = getApps()[0];
    return app;
  }

  const serviceAccount = getServiceAccount();

  // If there's no service account, we can't initialize.
  // This prevents the app from crashing on the server.
  if (!serviceAccount) {
    console.warn("FIREBASE_SERVICE_ACCOUNT environment variable not found or invalid. Firebase Admin SDK could not be initialized.");
    return undefined;
  }
  
  // This is the only case where we need to initialize a new app.
  try {
    app = initializeApp({
      credential: cert(serviceAccount),
    });
    return app;
  } catch (e) {
    console.error("Error initializing Firebase Admin SDK:", e);
    return undefined;
  }
}
